# Generated by Django 4.0.5 on 2022-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='dni',
        ),
        migrations.AddField(
            model_name='personal',
            name='telefono',
            field=models.CharField(default=0, max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automovil',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Suv'), (3, 'Hatchback'), (4, 'Deportivo'), (5, 'Van'), (6, 'Pick up')], verbose_name='Tipo'),
        ),
    ]
