# Generated by Django 4.0.5 on 2022-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0003_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatares'},
        ),
        migrations.AddField(
            model_name='automovil',
            name='condicion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Usado')], default=0, verbose_name='Condicion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automovil',
            name='kms',
            field=models.FloatField(default=1, verbose_name='Kilometros'),
            preserve_default=False,
        ),
    ]
