# Generated by Django 4.0.5 on 2022-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0004_alter_avatar_options_automovil_condicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='anio',
            field=models.FloatField(default=1, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
