# Generated by Django 4.0.5 on 2022-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0005_automovil_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='anio',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
    ]
