# Generated by Django 4.0.5 on 2022-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0006_alter_automovil_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='condicion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Usado')], verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
