# Generated by Django 4.0.5 on 2022-07-19 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appautomoviles', '0007_automovil_imagen_alter_automovil_condicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Appautomoviles.automovil')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
