# Generated by Django 4.0.5 on 2022-07-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0008_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='body',
            new_name='comentario',
        ),
    ]
