# Generated by Django 4.0.5 on 2022-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appautomoviles', '0009_rename_body_comentario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre y apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('datos_automovil', models.TextField(verbose_name='(Marca / Modelo / Tipo / Color / Año / Kms)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
